// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plgfwnmzzwcinwtddkri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsZ2Z3bm16endjaW53dGRka3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MjA0MjAsImV4cCI6MjA1ODQ5NjQyMH0.wtROqINs_E87tTLnTEo5s_Pa9FI8IJYPXTpeXamD8Mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);